services:
  app:
    container_name: app
    build:
      dockerfile: .dockerfile
      context: .
    command: ${CMD}
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - net

volumes:
  pgdata:
  redisdata:

networks:
  net:
    driver: bridge
